//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dersler
    {
        public int ders_id { get; set; }
        public string ders_kod { get; set; }
        public string ders_adi { get; set; }
        public Nullable<int> Bolum_id { get; set; }
        public Nullable<int> sinif { get; set; }
        public string donem { get; set; }
    
        public virtual bolum bolum { get; set; }
    }
}
