//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fakulte
    {
        public fakulte()
        {
            this.bolums = new HashSet<bolum>();
        }
    
        public int fak_id { get; set; }
        public string C_fak_name { get; set; }
    
        public virtual ICollection<bolum> bolums { get; set; }
    }
}
